### ISSUE TITLE
Get exception when running doxx --source lib --target docs

### ISSUE THREAD

**Issue by rexwang** [FGRibreau/doxx#64]
I get this error when trying to parse javascript files:

```javascript
/usr/local/lib/node_modules/doxx/node_modules/marked/lib/marked.js:1215
    throw e;
          ^
TypeError: Cannot read property 'replace' of undefined
Please report this to https://github.com/chjj/marked.
    at Lexer.lex (/usr/local/lib/node_modules/doxx/node_modules/marked/lib/marked.js:137:5)
    at Function.Lexer.lex (/usr/local/lib/node_modules/doxx/node_modules/marked/lib/marked.js:128:16)
    at marked (/usr/local/lib/node_modules/doxx/node_modules/marked/lib/marked.js:1207:31)
    at module.exports (/usr/local/lib/node_modules/doxx/lib/doxx.js:116:11)
    at Object.<anonymous> (/usr/local/lib/node_modules/doxx/bin/doxx:42:1)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
```

**Comment by whit1440** [comment]
I got this error when I had a blank or non existent README.md file.

**Comment by FGRibreau** [comment]
Hello @rexwang @whit1440 as you can see in the output, the error must be reported to marked, not doxx

```
Please report this to https://github.com/chjj/marked.
```

Closing :)

**Comment by whit1440** [comment]
Maybe I'm reading something in the code wrong but to me it looks like in lib/doxx.js it
* tries to find a readme file at line 96
* looks in the file system for that file on line 98
* warns that no file is found on line 101
* one final attempt to populate the readme  on line 104
* passes what is has to `marked` package on line 116

I'd guess that it's passing in an undefined value to marked and marked is failing hard. Is marked expected to handle accepting an undefined value? I agree that marked should perhaps fail with more grace but en lieu of that you may want to consider making your readme requirements a little clearer. I see you have the option called out in bin/doxx but not in your README.md.

**Comment by FGRibreau** [comment]
Oh I see, so the only thing to do is to change lines around L.116 and not pass an empty readme to marked, right?
If so, no problem, send me a PR and I'll merge it to master :)
